--Define Database
Use 
    Project;

------------------------------------

--select all table
SELECT 
    * 
FROM 
    customer_shopping_behavior;

---------------------------------------
--Modifiy:
ALTER TABLE
    customer_shopping_behavior
ALTER COLUMN Review_Rating DECIMAL(2)

------------------------------------------
--Business requirement Questions:

--1. Find out the total no.of customers?
SELECT
    COUNT('Customer ID') AS Total_no_customers
FROM
    customer_shopping_behavior;

-----------------------------------------
--2. Find of the customers gendervise?

SELECT 
     Gender,
    COUNT(*) AS Count
FROM 
    customer_shopping_behavior
WHERE 
    Gender IN ('Male', 'Female')
GROUP BY
     Gender;

---------------------------------------
--Q3. What is the total revenue generated by male vs. female customers?

SELECT 
	gender,
	sum(purchase_amount) AS Revenue
FROM
	customer_shopping_behavior
GROUP BY
	gender
ORDER BY
    Revenue DESC;
--------------------------------------------
--Q4. Which customers used a discount but still more than the average purchase amount?

SELECT
    Customer_ID,
    Purchase_Amount
FROM
    customer_shopping_behavior
WHERE
    Discount_Applied='YES' 
    AND
         Purchase_Amount >= (SELECT AVG(Purchase_Amount) FROM customer_shopping_behavior);

------------------------------------------------------------------
--Q5. Compare the average purchase amount between standard and express shipping.

SELECT
    Shipping_Type,
    ROUND(AVG(Purchase_Amount),2) AS Shipping_purchase_amount
FROM
    customer_shopping_behavior
WHERE
    Shipping_Type IN ('Standard','Express')
GROUP BY
    Shipping_Type
ORDER BY
    Shipping_purchase_amount DESC;

--------------------------------------------------------------------
--Q6. Which are the top 5 product with the highest average review rating?

SELECT
    Item_Purchased,
    ROUND(AVG(Review_Rating),2) AS Average_Product_Rating
FROM
    customer_shopping_behavior
GROUP BY
    Item_Purchased
ORDER BY
    AVG(Review_Rating) DESC
OFFSET 5 ROWS FETCH NEXT 5 ROWS ONLY;

----------------------------------------------------------
--Q7. Do subcribed customers spend more? compare average spend and total 
--revenue between subscribers and non-subscribers.

SELECT
    Subscription_Status,
    COUNT(Customer_Id) AS Total_Customers,
    ROUND(AVG(Purchase_Amount),2) AS Avg_spend,
    ROUND(SUM(Purchase_Amount),2) AS Total_revenue
FROM
    customer_shopping_behavior
GROUP BY
    Subscription_Status
ORDER BY
    Total_revenue DESC,
    Avg_spend DESC;

---------------------------------------------------------------
--Q8. Which 5 products have the highest percentage of purchases with discounts applied?

SELECT
    Item_Purchased,
    ROUND(100.0 * SUM(CASE WHEN Discount_Applied = 'YES' THEN 1 ELSE 0 END)/ COUNT(*),2) 
    AS Discount_rate
FROM
    customer_shopping_behavior
GROUP BY
    Item_Purchased
ORDER BY
    Discount_rate DESC
OFFSET 5 ROWS FETCH NEXT 5 ROWS ONLY;

-------------------------------------------------------
--Q9. Segment customers into New, Rating, and Loyal based on their 
--total number of previous purchases, and show the count of each segment orderwise.

WITH Customer_Type AS
(
    SELECT
        Customer_Id,
        Previous_Purchases,
    CASE
        WHEN
            Previous_Purchases =1 THEN 'New'
        WHEN
            Previous_Purchases BETWEEN 2 AND 10 THEN 'Returning'
        ELSE
            'Loyal'
        END AS Customer_segment
    FROM
        customer_shopping_behavior
)
SELECT
    Customer_segment,
    COUNT(*) AS 'Number of Customers'
FROM
    Customer_Type
GROUP BY
    Customer_segment
ORDER BY
    2 DESC;

--------------------------------------------------------
--Q10. What are the top 3 most puchased products within each category?

WITH
    Item_Counts AS
(
    SELECT
        Category,
        Item_Purchased,
        COUNT(Customer_Id) AS Total_orders,
        ROW_NUMBER() OVER (PARTITION BY Category ORDER BY COUNT(Customer_Id) DESC) AS Item_rank
    FROM
        customer_shopping_behavior
    GROUP BY
        Category,
        Item_Purchased
)
SELECT
    Item_rank,
    Item_Purchased,
    Total_orders
FROM
    Item_Counts
WHERE
    Item_rank <=3;

-----------------------------------------------------------
--Q11. Are customers who are repeat buyers (more than 5 previous puchases) also likely to subscribe?

SELECT
    Subscription_Status,
    COUNT(Customer_Id) AS Repeat_Buyers
FROM
    customer_shopping_behavior
WHERE
    Previous_Purchases > 5
GROUP BY
    Subscription_Status;

------------------------------------------------------
--Q12. What is the revenue contribution of each age group?

SELECT
    Age,
    SUM(Purchase_Amount) AS Total_revenue
FROM
    customer_shopping_behavior
GROUP BY
    Age
ORDER BY
    Total_revenue;

-------------------x-------------------